### ISSUE TITLE
Code and model does not match

### ISSUE THREAD

**Issue by tuhinexe** [akshaynstack/reactai#2]
In the code, you are using OpenAI for completions but you are passing `claude-3-5sonnet` in the request body. It should not work as OpenAI is not compatible with this model. Can you explain what is going on here?

**Comment by tuhinexe** [comment]
![image](https://github.com/user-attachments/assets/712954f1-9e28-4e04-8bbe-1178d65918d4)


This image shows you are using OpenAI but the available models on the client side are all Claude AI models.

This does not make sense!

**Comment by akshaynstack** [comment]
OpenAI SDK allows baseurl and apikey as parameters, I just passed base url of claude ai into openai nodejs sdk

like this 

```tsx
const openai = new OpenAI({
  apiKey: process.env.LLM_API_KEY,
  baseURL: process.env.LLM_BASE_URL,
});
```

**Comment by tuhinexe** [comment]
That should not work. OpenAI client does not allow any "anthropic" endpoints and models. It will throw a 404 straight away.

Can you elaborate what do you mean by claude AI's base URL?

**Comment by akshaynstack** [comment]
All my api keys are added to openrouter and openrouter gives you a base url so that can be used as baseurl and apikey as usual.

See docs here for openrouter - [https://openrouter.ai/docs/quick-start](https://openrouter.ai/docs/quick-start)

```tsx
import OpenAI from "openai"

const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: $OPENROUTER_API_KEY,
  defaultHeaders: {
    "HTTP-Referer": $YOUR_SITE_URL, // Optional, for including your app on openrouter.ai rankings.
    "X-Title": $YOUR_APP_NAME, // Optional. Shows in rankings on openrouter.ai.
  }
})

async function main() {
  const completion = await openai.chat.completions.create({
    model: "openai/gpt-3.5-turbo",
    messages: [
      {
        "role": "user",
        "content": "What is the meaning of life?"
      }
    ]
  })

  console.log(completion.choices[0].message)
}
main()
```

**Comment by tuhinexe** [comment]
Got it. Thanks for the explanation. Good Work :+1:
